export enum CanvasEvents {
  ADD_ROOT_NODE = "CANVAS/ADD_ROOT_NODE",
  REMOVE_ROOT_NODE = "CANVAS/REMOVE_ROOT_NODE",
  MOVE_ROOT_NODE = "CANVAS/MOVE_ROOT_NODE",
  SET_ROOT_NODE_TITLE = "CANVAS/SET_ROOT_NODE_TITLE",
  SELECT_FROM_ROOT_NODE = "CANVAS/SELECT_FROM_ROOT_NODE",
  CONNECT_ROOT_NODES = "CANVAS/CONNECT_ROOT_NODES",
  DELETE_CONNECTION = "CANVAS/DELETE_CONNECTION",
  DELETE_ALL_CONNECTIONS = "CANVAS/DELETE_ALL_CONNECTIONS"
}
