export enum CanvasEvents {
  ADD_ROOT_NODE = "CANVAS/ADD_ROOT_NODE",
  REMOVE_ROOT_NODE = "CANVAS/REMOVE_ROOT_NODE",
  MOVE_ROOT_NODE = "CANVAS/MOVE_ROOT_NODE",
  SET_ROOT_NODE_TITLE = "CANVAS/SET_ROOT_NODE_TITLE"
}
